name: Update Vintage Story

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "0 5 * * *" # Runs at 5:00 AM UTC daily

jobs:
  update-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Update flake.lock # mitigate user downloading multiple revisions of nixpkgs/nixos-unstable
        run: |
          nix flake update

      - name: Run Update Script
        run: nix run .#update

      - name: Validate that flake builds after updating # best practice
        run: nix build .

      - name: Validate overlay output
        run: nix flake check

      - name: Commit and Push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update vintage story version"
          file_pattern: "sources.json flake.lock"
